"""empty message

Revision ID: 1e97ad110872
Revises: None
Create Date: 2015-04-20 19:40:35.793658

"""

# revision identifiers, used by Alembic.
revision = '1e97ad110872'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activate_token', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('verified', sa.Boolean(name='verified'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UID', sa.String(length=32), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=False),
    sa.Column('ShortName', sa.String(length=128), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Groups', sa.String(length=64), nullable=True),
    sa.Column('UnitType', sa.String(length=4), nullable=True),
    sa.Column('EndPrices', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('LastUpdatePresta', sa.DateTime(), nullable=True),
    sa.Column('LastUpdateStockQ', sa.DateTime(), nullable=True),
    sa.Column('Quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_products')
    )
    op.create_index('ix_products_UID', 'products', ['UID'], unique=True)
    op.create_index('ix_products_order_number', 'products', ['order_number'], unique=True)
    op.create_table('user_password_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(name='used'), nullable=True),
    sa.Column('expiration_dt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_password_tokens_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_user_password_tokens')
    )
    op.create_index('ix_user_password_tokens_value', 'user_password_tokens', ['value'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_password_tokens_value', table_name='user_password_tokens')
    op.drop_table('user_password_tokens')
    op.drop_index('ix_products_order_number', table_name='products')
    op.drop_index('ix_products_UID', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
